name: inventory-api
owner: mathilde.gallouet@ansys.com
members:
- id: bob@ansys.com
  role: developer
  environments: []
- id: qa@ansys.com
  role: approver
  environments:
  - test
environments:
- name: dev
  gates: []
- name: test
  gates:
  - manual_approval
layer:
  namespace: inventory
  project_route: true
  subdomains:
  - inventory-admin
  ca_bundle_name: ansys-bundle
  enable_idp_token_exchange: false
