apiVersion: promoter.argoproj.io/v1alpha1
kind: ArgoCDCommitStatus
metadata:
  name: my-app-health
  namespace: promoter-system
spec:
  promotionStrategyRef:
    name: my-app
  applicationSelector:
    matchLabels:
      app-name: my-app
