apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionStrategy
metadata:
  name: my-app
  namespace: promoter-system
spec:
  activeCommitStatuses:
  - key: argocd-health
  environments:
  - autoMerge: true
    branch: stages/my-app-dev
  - autoMerge: true
    branch: stages/my-app-test
  gitRepositoryRef:
    name: fuji-factory
